{% set name = "airflow-priority" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/airflow-priority/airflow_priority-{{ version }}.tar.gz
  sha256: e0e5e2441fca0bac65b5cf5f71eff00f02baa9a2532ea0268131155ee760e44a

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - apache-airflow >=2,<3
  run_constrained:
    - airflow-config >=0.1.2

test:
  requires:
    - python ={{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - airflow_priority.common

about:
  home: https://github.com/airflow-laminar/airflow-priority
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Priority Tags for Airflow Dags
  description: Priority Tags for Airflow Dags
  dev_url: https://github.com/airflow-laminar/airflow-priority

extra:
  recipe-maintainers:
    - timkpaine
